import {
  GiCard10Clubs,
  GiCard10Diamonds,
  GiCard10Hearts,
  GiCard10Spades,
  GiCard2Clubs,
  GiCard2Diamonds,
  GiCard2Hearts,
  GiCard2Spades,
  GiCard3Clubs,
  GiCard3Diamonds,
  GiCard3Hearts,
  GiCard3Spades,
  GiCard4Clubs,
  GiCard4Diamonds,
  GiCard4Hearts,
  GiCard4Spades,
  GiCard5Clubs,
  GiCard5Diamonds,
  GiCard5Hearts,
  GiCard5Spades,
  GiCard6Clubs,
  GiCard6Diamonds,
  GiCard6Hearts,
  GiCard6Spades,
  GiCard7Clubs,
  GiCard7Diamonds,
  GiCard7Hearts,
  GiCard7Spades,
  GiCard8Clubs,
  GiCard8Diamonds,
  GiCard8Hearts,
  GiCard8Spades,
  GiCard9Clubs,
  GiCard9Diamonds,
  GiCard9Hearts,
  GiCard9Spades,
  GiCardAceClubs,
  GiCardAceDiamonds,
  GiCardAceHearts,
  GiCardAceSpades,
  GiCardJackClubs,
  GiCardJackDiamonds,
  GiCardJackHearts,
  GiCardJackSpades,
  GiCardJoker,
  GiCardKingClubs,
  GiCardKingDiamonds,
  GiCardKingHearts,
  GiCardKingSpades,
  GiCardQueenClubs,
  GiCardQueenDiamonds,
  GiCardQueenHearts,
  GiCardQueenSpades,
} from 'react-icons/gi';

export const cards = {
  Joker: GiCardJoker,
  AceClubs: GiCardAceClubs,
  AceDiamonds: GiCardAceDiamonds,
  AceHearts: GiCardAceHearts,
  AceSpades: GiCardAceSpades,
  '10Clubs': GiCard10Clubs,
  '10Diamonds': GiCard10Diamonds,
  '10Hearts': GiCard10Hearts,
  '10Spades': GiCard10Spades,
  '2Clubs': GiCard2Clubs,
  '2Diamonds': GiCard2Diamonds,
  '2Hearts': GiCard2Hearts,
  '2Spades': GiCard2Spades,
  '3Clubs': GiCard3Clubs,
  '3Diamonds': GiCard3Diamonds,
  '3Hearts': GiCard3Hearts,
  '3Spades': GiCard3Spades,
  '4Clubs': GiCard4Clubs,
  '4Diamonds': GiCard4Diamonds,
  '4Hearts': GiCard4Hearts,
  '4Spades': GiCard4Spades,
  '5Clubs': GiCard5Clubs,
  '5Diamonds': GiCard5Diamonds,
  '5Hearts': GiCard5Hearts,
  '5Spades': GiCard5Spades,
  '6Clubs': GiCard6Clubs,
  '6Diamonds': GiCard6Diamonds,
  '6Hearts': GiCard6Hearts,
  '6Spades': GiCard6Spades,
  '7Clubs': GiCard7Clubs,
  '7Diamonds': GiCard7Diamonds,
  '7Hearts': GiCard7Hearts,
  '7Spades': GiCard7Spades,
  '8Clubs': GiCard8Clubs,
  '8Diamonds': GiCard8Diamonds,
  '8Hearts': GiCard8Hearts,
  '8Spades': GiCard8Spades,
  '9Clubs': GiCard9Clubs,
  '9Diamonds': GiCard9Diamonds,
  '9Hearts': GiCard9Hearts,
  '9Spades': GiCard9Spades,
  JackClubs: GiCardJackClubs,
  JackDiamonds: GiCardJackDiamonds,
  JackHearts: GiCardJackHearts,
  JackSpades: GiCardJackSpades,
  QueenClubs: GiCardQueenClubs,
  QueenDiamonds: GiCardQueenDiamonds,
  QueenHearts: GiCardQueenHearts,
  QueenSpades: GiCardQueenSpades,
  KingClubs: GiCardKingClubs,
  KingDiamonds: GiCardKingDiamonds,
  KingHearts: GiCardKingHearts,
  KingSpades: GiCardKingSpades,
};
